import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9F9F9',
  },
  modalSuporte: {
    padding: 20,
    backgroundColor: '#F9F9F9',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitleSuporte: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#2D6A4F',
    marginBottom: 10,
  },
  modalTextSuporte: {
    fontSize: 16,
    color: '#333',
    textAlign: 'center',
    marginBottom: 20,
  },
  modalButtonSuporte: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#2D6A4F',
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 10,
  },
  buttonTextSuporte: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
  },
  header: {
    backgroundColor: '#058301',
    paddingVertical: 15,
    paddingHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFF',
  },
  profileSection: {
    alignItems: 'center',
    marginVertical: 30,
  },
  profileImage: {
    width: 150,
    height: 150,
    borderRadius: 100,
    borderWidth: 4,
    borderColor: '#058301',
  },
  iconOverlay: {
    position: 'absolute',
    bottom: 5,
    right: 5,
    backgroundColor: '#058301',
    borderRadius: 20,
    padding: 5,
  },
  userName: {
    fontSize: 30,
    fontWeight: '400',
    marginTop: 10,
    color: "#111",
  },
  input: {
    height: 42,
    width: '50%',
    backgroundColor: '#FFF',
    borderBottomWidth: 1.5,
    borderColor: '#556b2f',
    borderRadius: 6,
    paddingHorizontal: 10,
    fontSize: 15,
    marginVertical: 15,
    textAlign: 'center',
  },
  menuContainer: {
    marginVertical: 2,
    backgroundColor: '#FFF',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    margin: 15,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#EEE',
    borderRadius: 8,
  },
  menuIcon: {
    marginRight: 20,
  },
  menuText: {
    fontSize: 16,
    color: '#058301',
    fontWeight: "900",
  },
  logoutButton: {
    backgroundColor: 'red',
    marginHorizontal: '25%',
    marginVertical: '8%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    borderRadius: 10,
    height: 50,
  },
  logoutText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '900',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: '90%',
    height: '90%',
    backgroundColor: '#F9F9F9',
    alignItems: 'center',
    borderRadius: 12,
  },
  modalText: {
    fontSize: 16,
    textAlign: 'center',
    color: '#222',
    marginVertical: 50,
    width: '90%',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    backgroundColor: '#058301',
    borderRadius: 20,
    padding: 5,
  },
  propertyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 50,
    width: 300,
    backgroundColor: '#058301',
    borderRadius: 12,
    paddingHorizontal: 10,
    marginVertical: 50,

  },
  propertyIcon: {
    marginRight: 20,
    color: '#fff',
  },
  propertyName: {
    fontSize: 20,
    fontWeight: '900',
    color: '#fff',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 30,
  },
  emptyText: {
    fontSize: 14,
    color: '#888',
  },
  modalPlanos: {
    flex: 1,
    padding: 20,
  },
  headerContainer: {
    alignItems: 'center',
    marginBottom: 10,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 16,
    color: 'gray',
    textAlign: 'center',
  },
    editButton: {
    backgroundColor: '#fff',
    width: 35,
    height: 35,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default styles;
