import { StyleSheet } from 'react-native';

const colors = {
  primary: '#058301',
  secondary: '#fff',
  text: '#555',
  placeholder: '#B3B3B3',
  error: '#D32F2F',
  success: '#058301',
  disabled: '#ccc',
  border: '#058301',
  background: '#f9f9f9',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContainer: {
    flexGrow: 1,
    justifyContent: 'center',
  },
  authContainer: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  logo: {
    height: 120,
    width: '80%',
    resizeMode: 'contain',
    marginBottom: 30,
  },
  welcome: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 30,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 10,
  },
  label: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 8,
    color: colors.text,
    alignSelf: 'flex-start',
    marginLeft: '8%',
  },
  input: {
    height: 50,
    width: '85%',
    borderColor: colors.border,
    borderWidth: 1.5,
    marginBottom: 20,
    paddingHorizontal: 15,
    borderRadius: 12,
    backgroundColor: colors.secondary,
    fontSize: 16,
    color: colors.text,
  },
  passwordContainer: {
    flexDirection: 'row',
    width: '85%',
    alignItems: 'center',
    borderColor: colors.border,
    borderWidth: 1.5,
    borderRadius: 12,
    paddingHorizontal: 15,
    marginBottom: 20,
    backgroundColor: colors.secondary,
    height: 50,
  },
  passwordInput: {
    flex: 1,
    fontSize: 16,
    color: colors.text,
  },
  requisitosContainer: {
    marginBottom: 20,
    width: '85%',
    backgroundColor: colors.secondary,
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  valid: {
    color: colors.success,
    fontSize: 14,
    marginBottom: 4,
    fontWeight: '500',
  },
  invalid: {
    color: colors.error,
    fontSize: 14,
    marginBottom: 4,
    fontWeight: '500',
  },
  buttonContainer: {
    marginBottom: 15,
    width: '85%',
  },
  authButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  authButtonText: {
    fontSize: 18,
    color: colors.secondary,
    fontWeight: 'bold',
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.secondary,
    borderRadius: 12,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderWidth: 1.5,
    borderColor: '#ddd',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  googleIcon: {
    width: 24,
    height: 24,
    marginRight: 12,
  },
  googleButtonText: {
    fontSize: 16,
    color: '#333',
    fontWeight: '600',
  },
  disabledButton: {
    opacity: 0.6,
  },
  ou: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginVertical: 20,
    textAlign: 'center',
  },
  toggleText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: colors.primary,
    marginTop: 20,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  disabledText: {
    opacity: 0.6,
  },
});

export default styles;